#global var
region: "0"

#Docker application name which you want to pull, data format: Lists

docker_applications:
#  - adminmongo
#  - onlyofficedocumentserver
#  - phpmyadmin
#  - phppgadmin
#  - portainer
