  # Centos 
- block:
  - name: Install required packages
    yum:
      name: [device-mapper-persistent-data,lvm2]

  - name: Add repository
    template:
      src: docker.repo.jinja2
      dest: /etc/yum.repos.d/docker.repo
    when: ansible_distribution != 'Amazon'
        

  - name: Install Docker
    yum:
      name: [docker-ce,docker-ce-cli,containerd.io]
    when: ansible_distribution != 'Amazon'
    
  - name: Install Docker
    shell: amazon-linux-extras install docker -y
    when: ansible_distribution == 'Amazon'

  when: ansible_os_family == 'RedHat'

  # # Ubuntu
- block:
  - name: Install required packages
    apt:
      name: [apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common,libffi-dev,libssl-dev]
    

  - name:  Add Dockerâ€™s official GPG key
    apt_key:
      url:  https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88

  - name: Add repository 
    apt_repository:
      filename: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable
      
  - name: Install Docker
    apt:
      name: [docker-ce,docker-ce-cli,containerd.io]
        
  when: ansible_os_family == 'Debian'

- name: pip update requests
  pip:
    name: requests
    extra_args: " -U --ignore-installed"
    
- name: pip requirements
  pip:
    name: docker
    extra_args:  --ignore-installed

- name: Install Docker Compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

- name: Started Docker
  service:
    name: docker 
    enabled: yes
    state: restarted

- name: Restarted Docker
  service:
    name: docker 
    enabled: yes
    state: restarted

- name: Check Docker Version
  shell: docker -v
  register: docker_ver
  notify: Docker Version

# Docker application installation

- name: Install Docker applications
  include_tasks: apps_{{item}}.yml
  with_items: "{{docker_applications}}"
  when: docker_applications != none